---
- name: Test Windows Connectivity
  hosts: localhost
  gather_facts: false

  vars:
    ansible_host: 192.168.31.165
    ansible_user: ansibleadmin
    ansible_password: Password@123
    ansible_connection: winrm
    ansible_port: 5985
    ansible_winrm_transport: basic
    ansible_winrm_server_cert_validation: ignore
    venv_path: /tmp/python_env
    chromium_dir: /tmp/chromium
    chromium_zip: /tmp/chromium.zip

  tasks:

    - name: Test WinRM connectivity
      win_ping:
      delegate_to: "{{ ansible_host }}"

    - name: Get hostname
      win_shell: hostname
      register: hostname_result
      delegate_to: "{{ ansible_host }}"

    - name: Display hostname
      debug:
        msg: "Connected successfully to {{ hostname_result.stdout }}"
    
    - name: Create Python VirtualEnv
      ansible.builtin.command:
        cmd: python3 -m venv {{ venv_path }}
      args:
        creates: "{{venv_path}}/bin/python"

    - name: Install python module
      ansible.builtin.pip:
        virtualenv: "{{ venv_path }}"
        name: 
          - pyppeteer
          - requests
          - beautifulsoup4

    - name: Create Chromium Directory
      ansible.builtin.file:
        path: "{{ chromium_dir }}"
        state: directory
        mode: '0755'
    
    - name: Download Chromium
      ansible.builtin.get_url:
        url: "https://storage.googleapis.com/chromium-browser-snapshots/Win_x64/1000027/chrome-win.zip"
        dest: "{{ chromium_zip }}"
        mode: '0644'

    - name: Extract Chromium
      ansible.builtin.unarchive:
        src: "{{ chromium_zip }}"
        dest: "{{ chromium_dir }}"
        remote_src: true

    - name: Verfiy Chromium exists
      ansible.builtin.stat:
        path: "{{ chromium_dir }}/chrome-win/chrome"
      register: chrome_stat

    - name: Fail if Chromium missing
      ansible.builtin.fail:
        msg: "Chromium extraction failed"
      when: not chrome_stat.stat.exists
